angular.module('jwtApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('views/auth/login.html',
    "<div class=\"login-color\"> <div class=\"login-container\" layout=\"column\" layout-align=\"center center\"> <div class=\"login-form-container md-inline-form\" layout=\"column\" layout-align=\"center center\" ng-cloak> <!--    top login picture--> <div class=\"profile_pic\"> </div> <h4>Login JWT</h4> <form name=\"loginForm\"> <div layout-wrap layout=\"column\" layout-align=\"center center\"> <!--        inputs for username and password--> <md-input-container flex=\"66\" ng-class=\"{'md-input-invalid':loginForm.username.$invalid && loginPressed}\"> <label>User</label> <input id=\"user\" name=\"username\" ng-model=\"login.username\" required md-maxlength=\"20\" ng-keyup=\"$event.keyCode == 13 ? scopedFunctions.submit() : null\"> <div ng-messages=\"loginForm.username.$error\" ng-show=\"loginForm.username.$dirty && loginPressed\"> </div> </md-input-container> <md-input-container flex=\"66\" ng-class=\"{'md-input-invalid':loginForm.password.$invalid && loginPressed}\"> <label> Password </label> <input type=\"password\" name=\"password\" ng-model=\"login.password\" required md-maxlength=\"20\" ng-keyup=\"$event.keyCode == 13 ? scopedFunctions.submit() : null\"> <div ng-messages=\"loginForm.password.$error\" ng-show=\"loginForm.password.$dirty && loginPressed\"> </div> </md-input-container> </div> </form> <section layout=\"column\"> <section class=\"layout-row\"> <md-button class=\"md-raised md-primary col-md-auto\" ng-click=\"scopedFunctions.submit()\">LOGIN</md-button> </section> </section> <section layout=\"row\"> <div class=\"login-messages\" ng-repeat=\"(key,error) in errors\"> <span class=\"text-danger\">{{error}}</span> </div> </section> </div> </div> </div>"
  );


  $templateCache.put('views/firstPage.html',
    "<div class=\"row\"> <div class=\"col-md-12 col-sm-12 col-xs-12\"> <div class=\"x_panel\"> <div class=\"x_title\"> <h2>Your token authentication</h2> <ul class=\"nav navbar-right panel_toolbox\"> </ul> <div class=\"clearfix\"></div> </div> <div class=\"x_content\"> <table class=\"table\"> <thead> <tr> <th>#</th> <th>Username</th> <th>ROLES</th> </tr> </thead> <tbody> <tr> <th scope=\"row\">1</th> <td>{{authDetails.username}}</td> <td>{{authDetails.authorities}}</td> </tr> </tbody> </table> </div> </div> </div> <div class=\"col-md-12 col-sm-12 col-xs-12\"> <div class=\"x_panel\"> <div class=\"x_title\"> <h2>Simple resource permissions test (Check console for more information)</h2> <div class=\"clearfix\"></div> </div> <div class=\"x_content\"> <form class=\"form-horizontal form-label-left\" novalidate> <div class=\"ln_solid\"></div> <div class=\"form-group\"> <div class=\"col-md-6 col-md-offset-4\"> <button class=\"btn btn-primary\" ng-click=\"pageFunctions.getUserData()\">Try user data</button> <button class=\"btn btn-primary\" ng-click=\"pageFunctions.getGuestData()\">Try guest data</button> <button class=\"btn btn-success\" ng-click=\"pageFunctions.getAdminData()\">Try admin data</button> <button class=\"btn btn-success\" ng-click=\"pageFunctions.refreshToken()\">Refresh token</button> <button class=\"btn btn-danger\" ng-click=\"pageFunctions.logout()\">LOGOUT</button> </div> </div> </form> </div> </div> </div> </div>"
  );

}]);
